version: '3.8'
services:
  catalog-service:
    depends_on:
      - polar-postgres
    image: rbellini/catalog-service
    container_name: catalog-service
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
  
  polar-postgres:
    image: postgres:15.2
    container_name: polar-postgres
    ports:
      - 25432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  polar-redis:
    image: redis:7.0.11
    container_name: polar-redis
    ports:
      - "6379:6379"

  polar-rabbitmq:
    image: rabbitmq:3.12.1-management
    container_name: polar-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf