version: '3.8'
services:
  catalog-service:
    depends_on:
      - polar-postgres
    image: rbellini/catalog-service
    container_name: catalog-service
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
  
  polar-postgres:
    image: postgres:15.2
    container_name: polar-postgres
    ports:
      - 25432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  polar-redis:
    image: redis:7.0.11
    container_name: polar-redis
    ports:
      - "6379:6379"

  polar-rabbitmq:
    image: rabbitmq:3.12.1-management
    container_name: polar-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  
  polar-keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    container_name: polar-keycloak
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HTTP_PORT=9090
    ports:
      - "9090:9090"

  polar-ui:
    image: "polar-ui:latest"
    container_name: "polar-ui"
    ports:
    - 9004:9004
    environment:
    - PORT=9004
  
  grafana:
    image: grafana/grafana:9.5.6
    container_name: grafana
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./observability/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./observability/grafana/grafana.ini:/etc/grafana/grafana.ini
    
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"
  
  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:2.8.2-amd64
    container_name: fluent-bit
    ports:
      - "24224:24224"
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf