include('../../../../config-service/Tiltfile')
include('../../../../edge-service/Tiltfile')
include('../../../../order-service/Tiltfile')
include('../../../../catalog-service/Tiltfile')
include('../../../../dispatcher-service/Tiltfile')

update_settings(max_parallel_updates=1)
docker_prune_settings(disable = False, max_age_mins = 30, num_builds = 3, keep_recent = 1) 